# Default values for sensor-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

qualys:
  namespace: "qualys"
  customerID: "<Provide CUSTOMERID>"
  activationID: "<Provide ACTIVATIONID>"
  # <POD_URL_from_sensor_deployment_guide_page_13_include_https://>
  pod_url: ""
  containerlaunchtimeout: "10"
  image: "qualys/qcs-sensor:latest"  #Qualys sensor image location
  imagePullPolicy: "IfNotPresent"  
  # args for configuring the sensor - see documentaiton on sensor deployment
  args: "[\"--k8s-mode\"]"
  cpu: "0.2"
  # this toleration is to have the daemonset runnable on master nodes
  # set it to true it if want your masters to run sensor pod
  toleration: false
  tolerationeffect : NoSchedule
  # if proxy is required to connect Qualys Cloud, set the below value to true
  httpsproxy: false
  httpsproxyvalue: "<proxy FQDN or Ip address>:<port#>"
  # if proxy required for registry sensor version 1.21.0 or later used for a public registry, set the below value to true
  registryhttpsproxy: false
  registryhttpsproxyvalue: "<proxy FQDN or Ip address>:<port#>"
  # if proxy(with CA cert) required to connect Qualys Cloud
  proxycert: false
  proxycertpath: "<proxy certificate path>"
  # Peristent volume host path
  withpersistentvol: true
  persistentvolhostpath: "/usr/local/qualys/sensor/data"
  # if k8s version is 1.17 and earlier then change apiVersion to "rbac.authorization.k8s.io/v1beta1"
  apiVersion: "rbac.authorization.k8s.io/v1" 
  # if using Docker HTTP socket with TLS, set the below value to true
  dockerTlsVerify: false
  dockerTlsVerifyValue: "1"
  tlscertpath: "<Path of directory of client certificates>"
  # Parameters to set sensor container memory limit. Please change values of parameters
  sensorContLimitMem: false
  sensorContLimitMemValue: "500Mi"
  sensorContRequestMemValue: "300Mi"
  # Parameters to set scanning container memory limit. Please change values of parameters
  scanningContMem: false
  scanningContLimitMemValue: "800Mi"
  scanningContReqMemValue: "300Mi"
